# Generated by Django 4.2.1 on 2023-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='proje_resimleri/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('profil', models.ImageField(upload_to='profile/')),
                ('garder', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
            ],
        ),
    ]
